"use client";

import { useState } from "react";
import { Button, Input, Label, ResponsiveModal } from "@repo/components";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@repo/components";
import { Info, Calendar as CalendarIcon } from "lucide-react";

interface CreateScheduleDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function CreateScheduleDialog({
  open,
  onOpenChange,
}: CreateScheduleDialogProps) {
  const [formData, setFormData] = useState({
    orderId: "#ORD-98745",
    companyName: "",
    address: "",
    amount: "",
    fuelType: "Petrol",
    time: "",
    driver: "",
    status: "",
    priority: "",
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    console.log("Creating schedule:", formData);
    onOpenChange(false);
  };

  const handleChange = (field: string, value: string) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
  };

  return (
    <ResponsiveModal
      open={open}
      onOpenChange={onOpenChange}
      size="md"
      title="Schedule Delivery"
    >
      <form onSubmit={handleSubmit} className="space-y-6">
        {/* Description */}
        <p className="text-sm text-muted-foreground">
          Fill in the details below to create a schedule delivery order.
        </p>

        {/* Order ID */}
        <div className="space-y-2">
          <Label htmlFor="orderId">Order ID</Label>
          <Input
            id="orderId"
            value={formData.orderId}
            onChange={(e) => handleChange("orderId", e.target.value)}
            disabled
            className="bg-muted"
          />
          <div className="flex items-center gap-2 text-xs text-muted-foreground">
            <Info className="h-3 w-3" />
            <span>Order id is auto generated by system</span>
          </div>
        </div>

        {/* Company Name */}
        <div className="space-y-2">
          <Label htmlFor="companyName">Company Name</Label>
          <Select
            value={formData.companyName}
            onValueChange={(value) => handleChange("companyName", value)}
          >
            <SelectTrigger id="companyName">
              <SelectValue placeholder="Select Client" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="metro">Metro Gas Station</SelectItem>
              <SelectItem value="city">City Fuel Hub</SelectItem>
              <SelectItem value="express">Express Gas</SelectItem>
            </SelectContent>
          </Select>
        </div>

        {/* Address */}
        <div className="space-y-2">
          <Label htmlFor="address">Address</Label>
          <Input
            id="address"
            placeholder="Enter your address"
            value={formData.address}
            onChange={(e) => handleChange("address", e.target.value)}
          />
        </div>

        {/* Amount and Fuel Type */}
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label htmlFor="amount">Amount</Label>
            <Input
              id="amount"
              placeholder="Amount"
              value={formData.amount}
              onChange={(e) => handleChange("amount", e.target.value)}
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="fuelType">Fuel Type</Label>
            <Select
              value={formData.fuelType}
              onValueChange={(value) => handleChange("fuelType", value)}
            >
              <SelectTrigger id="fuelType">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="Petrol">Petrol</SelectItem>
                <SelectItem value="Diesel">Diesel</SelectItem>
                <SelectItem value="Gasoline">Gasoline</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>

        {/* Select Time */}
        <div className="space-y-2">
          <Label htmlFor="time">Select Time</Label>
          <div className="relative">
            <Input
              id="time"
              placeholder="Select Time"
              value={formData.time}
              onChange={(e) => handleChange("time", e.target.value)}
            />
            <CalendarIcon className="absolute right-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          </div>
        </div>

        {/* Driver */}
        <div className="space-y-2">
          <Label htmlFor="driver">Driver</Label>
          <Select
            value={formData.driver}
            onValueChange={(value) => handleChange("driver", value)}
          >
            <SelectTrigger id="driver">
              <SelectValue placeholder="Select driver" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="john">John Smith</SelectItem>
              <SelectItem value="jane">Jane Doe</SelectItem>
              <SelectItem value="mike">Mike Wilson</SelectItem>
            </SelectContent>
          </Select>
        </div>

        {/* Status */}
        <div className="space-y-2">
          <Label htmlFor="status">Status</Label>
          <Select
            value={formData.status}
            onValueChange={(value) => handleChange("status", value)}
          >
            <SelectTrigger id="status">
              <SelectValue placeholder="Select Status" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="scheduled">Scheduled</SelectItem>
              <SelectItem value="assigned">Assigned</SelectItem>
              <SelectItem value="in-progress">In Progress</SelectItem>
            </SelectContent>
          </Select>
        </div>

        {/* Priority */}
        <div className="space-y-2">
          <Label htmlFor="priority">Priority</Label>
          <Select
            value={formData.priority}
            onValueChange={(value) => handleChange("priority", value)}
          >
            <SelectTrigger id="priority">
              <SelectValue placeholder="Select priority" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="high">High</SelectItem>
              <SelectItem value="medium">Medium</SelectItem>
              <SelectItem value="low">Low</SelectItem>
            </SelectContent>
          </Select>
        </div>

        {/* Submit Button */}
        <Button
          type="submit"
          className="w-full bg-primary hover:bg-primary-foreground"
        >
          Create New Schedule
        </Button>
      </form>
    </ResponsiveModal>
  );
}
